# site settings
title: Nickolodeon
subtitle: by HTML5 UP
email: sjeon0730@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://nickolodeon98.github.io" # the base hostname & protocol for your site
author:
street_address: Odong-ro 40, Seo-gu
city: Incheon
state: Gyeonggi-do
zip_code: 22657
country: Republic of Korea
phone: 010-0000-0000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Nickolodeon98
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/seunghwan-jeon-604139208/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
